### ISSUE TITLE
安装好插件以后运行报错

### ISSUE THREAD

**Issue by XiaoLong2333** [bot-ssttkkl/nonebot-plugin-pixivbot#168]
![图片](https://user-images.githubusercontent.com/42651551/235381500-a3272ba5-49d7-42a6-ac57-b5d16a59ab45.png)
是我没配置好数据库吗

**Comment by XiaoLong2333** [comment]
已经运行了更新指令了

**Comment by XiaoLong2333** [comment]
![图片](https://user-images.githubusercontent.com/42651551/235381894-ed37fe45-3b5c-4b69-b5bb-b13d07b166c6.png)
也已安装数据库环境，配置好命令以及token

**Comment by ssttkkl** [comment]
是你代理设置错误
________________________________
