### ISSUE TITLE
按tag搜图和按画师搜图报错，随机发图数量错误

### ISSUE THREAD

**Issue by TU-O0T** [bot-ssttkkl/nonebot-plugin-pixivbot#178]
![image](https://github.com/bot-ssttkkl/nonebot-plugin-pixivbot/assets/110141765/1f219005-0c76-4e85-a4c1-d46bd4194b5c)

按tag搜图报错
![image](https://github.com/bot-ssttkkl/nonebot-plugin-pixivbot/assets/110141765/691eaf46-b66d-4346-a0f9-7016ff7968ec)
按画师搜图报错
![G(~N8 1T%BHYB 1TJ358RUD](https://github.com/bot-ssttkkl/nonebot-plugin-pixivbot/assets/110141765/395d1d2d-130d-40ea-bcc8-e937a26836b8)
随机发图数量错误

**Comment by ssttkkl** [comment]
还没适配Nonebot2.0正式版，最近没什么空，可能得咕一段时间
________________________________
From: TU-O0T ***@***.***>
Sent: Friday, June 9, 2023 9:34:05 PM
To: bot-ssttkkl/nonebot-plugin-pixivbot ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [bot-ssttkkl/nonebot-plugin-pixivbot] 按tag搜图和按画师搜图报错，随机发图数量错误 (Issue #178)


[image]<https://user-images.githubusercontent.com/110141765/244705818-1f219005-0c76-4e85-a4c1-d46bd4194b5c.png>

按tag搜图报错
[image]<https://user-images.githubusercontent.com/110141765/244705693-691eaf46-b66d-4346-a0f9-7016ff7968ec.png>
按画师搜图报错
[G(~N8 1T%BHYB 1TJ358RUD]<https://user-images.githubusercontent.com/110141765/244705997-395d1d2d-130d-40ea-bcc8-e937a26836b8.png>
随机发图数量错误

―

**Comment by ssttkkl** [comment]
1.9.0版本已修复
