### ISSUE TITLE
KeyError: '_matched_groups'

### ISSUE THREAD

**Issue by noc228076** [bot-ssttkkl/nonebot-plugin-pixivbot#180]
无法获取图片
![image](https://github.com/bot-ssttkkl/nonebot-plugin-pixivbot/assets/107999044/119c0282-be2b-4e2e-9eee-d4f130eabb5c)
![image](https://github.com/bot-ssttkkl/nonebot-plugin-pixivbot/assets/107999044/cc5663d8-7a80-4a30-bdf5-422b3af63e82)

**Comment by ssttkkl** [comment]
1.9.0版本已修复
