### ISSUE TITLE
数据库经常出现locked错误

### ISSUE THREAD

**Issue by 250king** [bot-ssttkkl/nonebot-plugin-pixivbot#200]
详情https://transmedia-studio.sentry.io/share/issue/8a6351b225e34250b284f2ed93cee792/

**Comment by ssttkkl** [comment]
可以通过禁用缓存缓解
`pixiv_use_local_cache=False`

根本的解决方案是使用postgresql，或者等我实现文件缓存（

**Comment by ssttkkl** [comment]
v2.0.3默认使用文件缓存，应该能解决大部分这种场景
