### ISSUE TITLE
使用权限组关闭r18被拒绝

### ISSUE THREAD

**Issue by ABKQPO** [bot-ssttkkl/nonebot-plugin-pixivbot#215]
permission deny --sbj all --srv nonebot_plugin_pixivbot.r18
'nonebot_plugin_pixivbot.r18' 拒绝 'all'

以下是插件权限节点
nonebot
└── nonebot_plugin_pixivbot
    ├── common
    │   ├── illust
    │   ├── ranking
    │   ├── more
    │   ├── random_bookmark
    │   ├── random_illust
    │   ├── random_recommended_illust
    │   ├── random_related_illust
    │   └── random_user_illust
    ├── illust_link
    ├── schedule
    │   ├── receive
    │   └── manage
    ├── watch
    │   ├── receive
    │   └── manage
    ├── invalidate_cache
    ├── bind
    ├── help
    └── r18
        └── g

**Comment by ssttkkl** [comment]
这是关闭成功的意思
拒绝=拒绝其他人使用该功能
________________________________
发件人: ABKQPO ***@***.***>
发送时间: 2023年12月21日 23:56
收件人: bot-ssttkkl/nonebot-plugin-pixivbot ***@***.***>
抄送: Subscribed ***@***.***>
主题: [bot-ssttkkl/nonebot-plugin-pixivbot] 使用权限组关闭r18被拒绝 (Issue #215)


permission deny --sbj all --srv nonebot_plugin_pixivbot.r18
'nonebot_plugin_pixivbot.r18' 拒绝 'all'

以下是插件权限节点
nonebot
└── nonebot_plugin_pixivbot
├── common
│ ├── illust
│ ├── ranking
│ ├── more
│ ├── random_bookmark
│ ├── random_illust
│ ├── random_recommended_illust
│ ├── random_related_illust
│ └── random_user_illust
├── illust_link
├── schedule
│ ├── receive
│ └── manage
├── watch
│ ├── receive
│ └── manage
├── invalidate_cache
├── bind
├── help
└── r18
└── g

―
